title: Eli Sachs
email: easachs13@gmail.com
description: >-
  Sophistication through Simplicity
baseurl: ""
url: "https://www.easachs.com"

github_username:  easachs
linkedin_username: easachs

google_analytics: "G-RS80H21YWV"

theme: minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:title
  archive:
    output: true
    permalink: /archive/:title
  tag:
    output: true
    permalink: /tags/:title

jekyll-archives:
  enabled: tags
  layout: default

header_pages:
- _pages/projects.md
- _pages/posts.md
- _pages/resume.html
- _pages/contact.html
